version: '3.9'

services:
  db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: kerala
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1391
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: ./kerala
    volumes:
      - ./kerala:/app  # Maps the local Django project directory to /app in the container
    ports:
      - "8000:8000"
    command: sh -c "python manage.py makemigrations users && python manage.py migrate users && python manage.py makemigrations appointments && python manage.py migrate appointments && python manage.py makemigrations && python manage.py migrate && python manage.py run_admin && python manage.py users_create && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000 "
    depends_on:
      - db
    environment:
      - DEBUG=True  # Set Django debug mode for development
    restart: always  # Restart the container if it fails


  nginx:
    build:
      context: .
    volumes:
      - ./assets:/usr/share/nginx/html/assets
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - django
    environment:
      - DEBUG=True  # Set Django debug mode for development
    restart: always  # Restart the container if it fails

volumes:
  postgres_data: