version: '3.9'

services:
  db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: smarthospital 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1391
      TZ: Asia/Kolkata  # Ensure system timezone is set
      PGTZ: Asia/Kolkata  # PostgreSQL timezone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - init-scripts:/docker-entrypoint-initdb.d  # Mount a folder for initialization scripts

  django:
    build:
      context: ./kerala
    volumes:
      - ./kerala:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations users &&
             python manage.py makemigrations patients &&
             python manage.py migrate patients &&
             python manage.py migrate users &&
             python manage.py makemigrations appointments &&
             python manage.py migrate appointments &&
             python manage.py makemigrations monitor && 
             python manage.py migrate monitor &&
             python manage.py makemigrations cookie &&
             python manage.py migrate cookie &&
             python manage.py makemigrations &&
             python manage.py makemigrations service &&
             python manage.py migrate service &&
             python manage.py migrate &&
             python manage.py run_admin &&
             python manage.py users_create &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=True
    restart: always

  nginx:
    build:
      context: .
    volumes:
      - ./assets:/usr/share/nginx/html/assets
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/smarthospitalmaintain.com:/etc/letsencrypt/live/smarthospitalmaintain.com:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - /etc/letsencrypt/privkey.pem:/etc/letsencrypt/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    environment:
      - DEBUG=True
    restart: always

volumes:
  postgres_data:
  init-scripts:
