# Generated by Django 5.1.6 on 2025-02-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_monitoredappointment_new_data_userloginlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredappointment',
            name='new_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
