# Generated by Django 5.1.7 on 2025-04-03 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_historicalpatient_channel_historicalpatient_cio_and_more'),
        ('patients', '__first__'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='patient',
            name='primary_doctor',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient'),
        ),
        migrations.DeleteModel(
            name='HistoricalPatient',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
