# Generated by Django 5.1.5 on 2025-01-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Scheduled', 'Scheduled'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=20),
        ),
    ]
