# Generated by Django 5.1.5 on 2025-02-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttests',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='Blood Pressure in mmHg', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointmenttests',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='appointmenttests',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Temperature in °C', null=True),
        ),
        migrations.AlterField(
            model_name='appointmenttests',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('first_name', 'contact_number')},
        ),
    ]
