# Generated by Django 5.1.5 on 2025-02-04 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointmenttests_blood_pressure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in °C', null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('blood_pressure', models.CharField(blank=True, help_text='Blood Pressure in mmHg', max_length=20, null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Heart rate in beats per minute (BPM)', null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Respiratory rate in breaths per minute', null=True)),
                ('oxygen_saturation', models.FloatField(blank=True, help_text='Oxygen saturation percentage (SpO2)', null=True)),
                ('blood_sugar_level', models.FloatField(blank=True, help_text='Blood sugar level in mg/dL', null=True)),
                ('bmi', models.FloatField(blank=True, help_text='Body Mass Index (BMI)', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='appointments.appointment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
