# Generated by Django 5.1.6 on 2025-02-10 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_vitals'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('patient', 'appointment_date')},
        ),
    ]
