# Generated by Django 5.1.6 on 2025-02-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_updated_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='contact_number',
            field=models.CharField(default='0702940509', max_length=15),
        ),
        migrations.AddField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('first_name', 'contact_number', 'appointment_date')},
        ),
    ]
