# Generated by Django 5.1.6 on 2025-02-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default=None, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
