# Generated by Django 5.1.5 on 2025-01-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='doctor', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='docctor', max_length=100),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='first_name',
            field=models.CharField(default='receptionist', max_length=100),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='last_name',
            field=models.CharField(default='receptionist', max_length=100),
        ),
    ]
