# Generated by Django 5.1.5 on 2025-01-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('receptionist', 'receptionist'), ('doctor', 'doctor'), ('admin', 'admin')], default='Receptionist', max_length=20),
        ),
    ]
