# Generated by Django 5.1.6 on 2025-02-14 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userloginlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLoginLog',
        ),
    ]
