# Generated by Django 5.1.6 on 2025-02-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_userloginlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='last_name',
        ),
    ]
