# Generated by Django 5.1.5 on 2025-01-28 23:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cookie',
            name='user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
