# Generated by Django 5.1.5 on 2025-02-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0002_cookie_login_time_cookie_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
